# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8305cad4032c849dd98f07849c2156e66c833bd9850ce68b6017b69681120cf708e5dd6a7a65d49579c9cc392521ee351fa24fcbc8eb85643f04c10d282b3ec4

test:
  secret_key_base: 2b55c91ff0b5927f39ab678fe3fdfb782b3dd6be06d5aa90880487b2972b7d3dc70b09e5ffc7dee28efdc8bb9ba426e7a63ec62193a478e069ae0b93bca10b65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
